export const movies = [
  {
    "id": "MOV001",
    "title": "Interstellar",
    "genre_id": 1,
    "year": 2014,
    "director": "Christopher Nolan",
    "main_actors": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    "duration_minutes": 169,
    "synopsis": "Un equipo de exploradores utiliza un agujero de gusano para superar las limitaciones de los viajes espaciales y conquistar las vastas distancias de un viaje interestelar.",
    "rental_price": 3.99,
    "purchase_price": 14.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/interstellar.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    "tags": ["most-viewed", "favorites"]
  },
  {
    "id": "MOV002",
    "title": "El Origen",
    "genre_id": 1,
    "year": 2010,
    "director": "Christopher Nolan",
    "main_actors": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    "duration_minutes": 148,
    "synopsis": "Un ladrón que roba información corporativa a través de la tecnología de sueños compartidos recibe la tarea inversa de implantar una idea en la mente de un director ejecutivo.",
    "rental_price": 3.49,
    "purchase_price": 12.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/inception.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=RV9L7ui9Cn8",
    "tags": ["most-viewed"]
  },
  {
    "id": "MOV003",
    "title": "Parásitos",
    "genre_id": 2,
    "year": 2019,
    "director": "Bong Joon-ho",
    "main_actors": ["Song Kang-ho", "Choi Woo-shik", "Park So-dam"],
    "duration_minutes": 132,
    "synopsis": "La familia Ki-taek, sin trabajo, se interesa de forma peculiar por la rica familia Park para un servicio de empleo mutuo.",
    "rental_price": 4.49,
    "purchase_price": 16.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/parasite.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    "tags": ["favorites", "recent-added"]
  },
  {
    "id": "MOV004",
    "title": "La La Land: Una Historia de Amor",
    "genre_id": 3,
    "year": 2016,
    "director": "Damien Chazelle",
    "main_actors": ["Ryan Gosling", "Emma Stone"],
    "duration_minutes": 128,
    "synopsis": "Un músico de jazz y una aspirante a actriz se enamoran en Los Ángeles, una ciudad conocida por destrozar esperanzas y corazones.",
    "rental_price": 2.99,
    "purchase_price": 11.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/la_la_land.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=45s24h98iOc",
    "tags": []
  },
  {
    "id": "MOV005",
    "title": "Pulp Fiction",
    "genre_id": 4,
    "year": 1994,
    "director": "Quentin Tarantino",
    "main_actors": ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    "duration_minutes": 154,
    "synopsis": "Las vidas de dos sicarios de la mafia, un boxeador, la esposa de un gánster y un par de bandidos se entrelazan en cuatro historias de violencia y redención.",
    "rental_price": 2.49,
    "purchase_price": 10.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/pulp_fiction.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
    "tags": ["favorites"]
  },
  {
    "id": "MOV006",
    "title": "El Caballero Oscuro",
    "genre_id": 5,
    "year": 2008,
    "director": "Christopher Nolan",
    "main_actors": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    "duration_minutes": 152,
    "synopsis": "Cuando la amenaza conocida como el Guasón emerge de su misterioso pasado, causa estragos y caos en el pueblo de Gotham.",
    "rental_price": 3.99,
    "purchase_price": 15.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/dark_knight.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    "tags": ["most-viewed", "favorites"]
  },
  {
    "id": "MOV007",
    "title": "Forrest Gump",
    "genre_id": 6,
    "year": 1994,
    "director": "Robert Zemeckis",
    "main_actors": ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    "duration_minutes": 142,
    "synopsis": "Las presidencias de Kennedy y Johnson, Vietnam, Watergate y otros eventos históricos se ven a través de la perspectiva de un hombre de Alabama con un coeficiente intelectual bajo.",
    "rental_price": 2.79,
    "purchase_price": 11.49,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/forrest-gump.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=bLvqoHBptjg",
    "tags": []
  },
  {
    "id": "MOV008",
    "title": "Spider-Man: Un Nuevo Universo",
    "genre_id": 7,
    "year": 2018,
    "director": "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    "main_actors": ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
    "duration_minutes": 117,
    "synopsis": "Miles Morales se convierte en el Spider-Man de su realidad y une fuerzas con Spider-Men de otras dimensiones para salvar todo el universo.",
    "rental_price": 3.99,
    "purchase_price": 14.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/spiderman.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=g4Hbz2jLxvQ",
    "tags": ["recent-added"]
  },
  {
    "id": "MOV009",
    "title": "Coco",
    "genre_id": 7,
    "year": 2017,
    "director": "Lee Unkrich, Adrian Molina",
    "main_actors": ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt"],
    "duration_minutes": 105,
    "synopsis": "Un aspirante a músico, Miguel, se enfrenta a la prohibición ancestral de su familia de la música, y entra en la Tierra de los Muertos para encontrar a su tatarabuelo, un legendario cantante.",
    "rental_price": 3.49,
    "purchase_price": 13.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/coco.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=awzWdtCezDo",
    "tags": []
  },
  {
    "id": "MOV010",
    "title": "Dune",
    "genre_id": 1,
    "year": 2021,
    "director": "Denis Villeneuve",
    "main_actors": ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac"],
    "duration_minutes": 155,
    "synopsis": "El hijo de una noble casa feudal se embarca en un viaje para asegurar el futuro de su familia y su pueblo.",
    "rental_price": 4.99,
    "purchase_price": 18.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/dune.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=TTgk_iT8Uts",
    "tags": ["recent-added"]
  },
  {
    "id": "MOV011",
    "title": "Cadena Perpetua",
    "genre_id": 6,
    "year": 1994,
    "director": "Frank Darabont",
    "main_actors": ["Tim Robbins", "Morgan Freeman"],
    "duration_minutes": 142,
    "synopsis": "Dos hombres encarcelados se unen a lo largo de varios años, encontrando consuelo y eventual redención a través de actos comunes de decencia.",
    "rental_price": 3.29,
    "purchase_price": 13.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/cadena-perpetua.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=_znb1cUiQP8",
    "tags": []
  },
  {
    "id": "MOV012",
    "title": "Gladiador",
    "genre_id": 8,
    "year": 2000,
    "director": "Ridley Scott",
    "main_actors": ["Russell Crowe", "Joaquin Phoenix"],
    "duration_minutes": 155,
    "synopsis": "Un general romano traicionado busca venganza contra el corrupto emperador que asesinó a su familia y lo esclavizó.",
    "rental_price": 2.99,
    "purchase_price": 12.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/gladiator.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=P5ieIbInFpg",
    "tags": []
  },
  {
    "id": "MOV013",
    "title": "Vengadores: Endgame",
    "genre_id": 5,
    "year": 2019,
    "director": "Anthony Russo, Joe Russo",
    "main_actors": ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    "duration_minutes": 181,
    "synopsis": "A la deriva en el espacio sin comida ni agua, Tony Stark envía un mensaje a Pepper Potts mientras su suministro de oxígeno comienza a agotarse.",
    "rental_price": 4.99,
    "purchase_price": 19.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/avengers-endgame.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=KdL8ucqi1F8",
    "tags": ["most-viewed"]
  },
  {
    "id": "MOV014",
    "title": "Toy Story",
    "genre_id": 7,
    "year": 1995,
    "director": "John Lasseter",
    "main_actors": ["Tom Hanks", "Tim Allen"],
    "duration_minutes": 81,
    "synopsis": "Un vaquero de juguete se siente amenazado y celoso cuando aparece una nueva figura de acción del espacio en el cumpleaños de Andy.",
    "rental_price": 2.49,
    "purchase_price": 9.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/toy-story.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=v-PjgYDrg70",
    "tags": []
  },
  {
    "id": "MOV015",
    "title": "Titanic",
    "genre_id": 9,
    "year": 1997,
    "director": "James Cameron",
    "main_actors": ["Leonardo DiCaprio", "Kate Winslet"],
    "duration_minutes": 195,
    "synopsis": "Un joven artista pobre y una mujer de clase alta se enamoran a bordo del desafortunado viaje inaugural del RMS Titanic.",
    "rental_price": 2.79,
    "purchase_price": 10.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/titanic.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=tA_qMdzvCvk",
    "tags": []
  },
  {
    "id": "MOV016",
    "title": "Matrix",
    "genre_id": 1,
    "year": 1999,
    "director": "Lana Wachowski, Lilly Wachowski",
    "main_actors": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    "duration_minutes": 136,
    "synopsis": "Un programador de computadoras aprende el origen de la realidad y su papel en la guerra contra las máquinas.",
    "rental_price": 2.99,
    "purchase_price": 12.49,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/matrix.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=OM0tSTEQCQA",
    "tags": []
  },
  {
    "id": "MOV017",
    "title": "El Señor de los Anillos: La Comunidad del Anillo",
    "genre_id": 10,
    "year": 2001,
    "director": "Peter Jackson",
    "main_actors": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
    "duration_minutes": 178,
    "synopsis": "Un joven hobbit hereda un anillo que debe ser destruido para evitar que el Señor Oscuro Sauron esclavice la Tierra Media.",
    "rental_price": 3.79,
    "purchase_price": 14.49,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/el-senor-de-los-anillos.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=iFOucwxKRFE",
    "tags": ["favorites"]
  },
  {
    "id": "MOV018",
    "title": "Soul",
    "genre_id": 7,
    "year": 2020,
    "director": "Pete Docter, Kemp Powers",
    "main_actors": ["Jamie Foxx", "Tina Fey"],
    "duration_minutes": 100,
    "synopsis": "Un músico de jazz que tiene un concierto importante se encuentra varado en el 'Más allá' después de un accidente.",
    "rental_price": 3.99,
    "purchase_price": 15.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/soul.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=3QIdlo4uIVg",
    "tags": ["recent-added"]
  },
  {
    "id": "MOV019",
    "title": "Joker",
    "genre_id": 4,
    "year": 2019,
    "director": "Todd Phillips",
    "main_actors": ["Joaquin Phoenix", "Robert De Niro"],
    "duration_minutes": 122,
    "synopsis": "Arthur Fleck, un comediante de stand-up fallido, se embarca en un viaje a la locura y se convierte en una figura icónica del crimen.",
    "rental_price": 4.49,
    "purchase_price": 16.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/joker.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=ZMH8NWf9btw",
    "tags": []
  },
  {
    "id": "MOV020",
    "title": "El Gran Hotel Budapest",
    "genre_id": 11,
    "year": 2014,
    "director": "Wes Anderson",
    "main_actors": ["Ralph Fiennes", "Tony Revolori"],
    "duration_minutes": 99,
    "synopsis": "La aventura de Gustave H., un legendario conserje en el famoso Gran Hotel Budapest, entre las dos guerras mundiales.",
    "rental_price": 3.29,
    "purchase_price": 12.99,
    "available_for_rental": true,
    "available_for_purchase": true,
    "cover_image_url": "/posters/hotel-budapest.webp",
    "youtube_trailer_url": "https://www.youtube.com/watch?v=QXMGdqo03Yw",
    "tags": []
  }
]